source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SPHStringContentFillView_Example', :exclusive => true do
  pod "SPHStringContentFillView", :path => "../"
end

target 'SPHStringContentFillView_Tests', :exclusive => true do
  pod "SPHStringContentFillView", :path => "../"

  
end
